# Generated by Django 4.2.9 on 2024-02-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("propietarios", "0004_multa_monto_multa_resolucion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Novedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateField(verbose_name="Fecha de servicio")),
            ],
        ),
        migrations.CreateModel(
            name="PersonaNoGrata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=250, null=True)),
                ("apellido", models.CharField(blank=True, max_length=250, null=True)),
                ("telefono", models.CharField(blank=True, max_length=250, null=True)),
                ("direccion", models.CharField(blank=True, max_length=250, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("dni", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Votacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateField(verbose_name="Fecha de servicio")),
                (
                    "voto",
                    models.BooleanField(default=False, verbose_name="Voto a favor"),
                ),
                (
                    "lote",
                    models.ManyToManyField(to="propietarios.lote", verbose_name="Lote"),
                ),
            ],
        ),
    ]
