# Generated by Django 4.2.9 on 2024-02-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personanograta",
            name="patente",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
