# Generated by Django 4.2.9 on 2024-02-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expensas", "0001_initial"),
    ]

    operations = []
