# Generated by Django 4.2.9 on 2024-01-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propietarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lote",
            name="nro_lote",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="propietario",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
