# Generated by Django 4.2.9 on 2024-01-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propietarios", "0003_multa"),
    ]

    operations = [
        migrations.AddField(
            model_name="multa",
            name="Monto",
            field=models.DecimalField(
                decimal_places=2,
                default=10000,
                max_digits=8,
                verbose_name="Monto de multa",
            ),
        ),
        migrations.AddField(
            model_name="multa",
            name="Resolucion",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
