# Generated by Django 4.2.9 on 2024-02-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propietarios", "0009_alter_lote_nro_lote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lote",
            name="nro_lote",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
