# Generated by Django 4.2.9 on 2024-01-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=250, null=True)),
                ("direccion", models.CharField(blank=True, max_length=250, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("contratado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250)),
                ("descripcion", models.TextField()),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        default=10000,
                        max_digits=9,
                        verbose_name="Monto del gasto",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha de servicio")),
                (
                    "prestador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gastos.proveedor",
                    ),
                ),
            ],
        ),
    ]
