# Generated by Django 4.2.9 on 2024-01-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="pagado",
            field=models.BooleanField(default=False),
        ),
    ]
