# Generated by Django 4.2.9 on 2024-02-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0002_servicio_pagado"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="cuil",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
