# Generated by Django 4.2.9 on 2024-02-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0003_proveedor_cuil_proveedor_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="descripcion",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
