# Generated by Django 4.2.9 on 2024-02-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0004_proveedor_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="abonado",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=9, verbose_name="Monto abonado"
            ),
        ),
    ]
